name: Deploy Node.js app to Azure Web App - itct-discord-bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Use LTS version of Node.js or the version that matches your local development environment

      - name: Install npm dependencies
        run: npm install

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'itct-discord-bot'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_38FABC7B07CF4B58A2A4CB82F8B2ECAB }}
          package: .
